<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NewsletterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('newsletters')->insert([
            [
                'subject' => 'Newsletter 1',
                'content' => 'Content of newsletter 1',
                'status' => 'sent',
                'sent_at' => Carbon::now()->subDays(2),
                'recipient_count' => 100,
                'success_count' => 90,
                'failure_count' => 10,
                'from_email' => 'sender1@example.com',
                'from_name' => 'Sender One',
                'type' => 'regular',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([1, 2, 3, 4, 5, 6]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 2',
                'content' => 'Content of newsletter 2',
                'status' => 'queued',
                'sent_at' => null,
                'recipient_count' => 150,
                'success_count' => 0,
                'failure_count' => 0,
                'from_email' => 'sender2@example.com',
                'from_name' => 'Sender Two',
                'type' => 'promotional',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([7, 8, 9, 10, 11]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 3',
                'content' => 'Content of newsletter 3',
                'status' => 'failed',
                'sent_at' => Carbon::now()->subDays(5),
                'recipient_count' => 50,
                'success_count' => 0,
                'failure_count' => 50,
                'from_email' => 'sender3@example.com',
                'from_name' => 'Sender Three',
                'type' => 'transactional',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([12, 13, 14, 15, 16]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Repeat this block for a total of 10 newsletters
            [
                'subject' => 'Newsletter 4',
                'content' => 'Content of newsletter 4',
                'status' => 'sent',
                'sent_at' => Carbon::now()->subDays(7),
                'recipient_count' => 200,
                'success_count' => 190,
                'failure_count' => 10,
                'from_email' => 'sender4@example.com',
                'from_name' => 'Sender Four',
                'type' => 'regular',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([17, 18, 19, 20]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 5',
                'content' => 'Content of newsletter 5',
                'status' => 'draft',
                'sent_at' => null,
                'recipient_count' => 120,
                'success_count' => 0,
                'failure_count' => 0,
                'from_email' => 'sender5@example.com',
                'from_name' => 'Sender Five',
                'type' => 'promotional',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([21, 22, 23, 24]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 6',
                'content' => 'Content of newsletter 6',
                'status' => 'queued',
                'sent_at' => null,
                'recipient_count' => 180,
                'success_count' => 0,
                'failure_count' => 0,
                'from_email' => 'sender6@example.com',
                'from_name' => 'Sender Six',
                'type' => 'transactional',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([25, 26, 27, 28]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 7',
                'content' => 'Content of newsletter 7',
                'status' => 'sent',
                'sent_at' => Carbon::now()->subDays(3),
                'recipient_count' => 220,
                'success_count' => 210,
                'failure_count' => 10,
                'from_email' => 'sender7@example.com',
                'from_name' => 'Sender Seven',
                'type' => 'regular',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([29, 30, 31, 32]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 8',
                'content' => 'Content of newsletter 8',
                'status' => 'sent',
                'sent_at' => Carbon::now()->subDays(10),
                'recipient_count' => 300,
                'success_count' => 280,
                'failure_count' => 20,
                'from_email' => 'sender8@example.com',
                'from_name' => 'Sender Eight',
                'type' => 'promotional',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([33, 34, 35, 36]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 9',
                'content' => 'Content of newsletter 9',
                'status' => 'failed',
                'sent_at' => Carbon::now()->subDays(8),
                'recipient_count' => 50,
                'success_count' => 0,
                'failure_count' => 50,
                'from_email' => 'sender9@example.com',
                'from_name' => 'Sender Nine',
                'type' => 'transactional',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([37, 38, 39, 40]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'subject' => 'Newsletter 10',
                'content' => 'Content of newsletter 10',
                'status' => 'draft',
                'sent_at' => null,
                'recipient_count' => 150,
                'success_count' => 0,
                'failure_count' => 0,
                'from_email' => 'sender10@example.com',
                'from_name' => 'Sender Ten',
                'type' => 'regular',
                'unsubscribe_link' => 'http://example.com/unsubscribe',
                'sent_email_ids' => json_encode([41, 42, 43, 44]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
